import React from 'react';
import '@testing-library/jest-dom';
import { BrowserRouter } from 'react-router-dom';
import { render, screen } from '@testing-library/react';
import Search from '../components/Search';

describe('Input page renders as required', () => {
  const data = [
    {
      date: '2022-01-07',
      id: 'canarias',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/canarias',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Canarias',
      name_es: 'Canarias',
      name_it: 'Canarias',
      source: 'John Hopkins University',
      sub_regions: [
        {
          date: '2021-03-10',
          id: 'tenerife',
          name: 'Tenerife',
          name_es: 'Tenerife',
          name_it: 'Tenerife',
          source: ' Consejería de Sanidad Gobierno de Canarias',
          today_confirmed: 17788,
          today_deaths: 0,
          today_new_confirmed: 112,
          today_new_deaths: 0,
          today_vs_yesterday_confirmed: 0.006336275175379047,
          today_vs_yesterday_deaths: null,
          yesterday_confirmed: 17676,
          yesterday_deaths: 0,
        },
        {
          date: '2021-03-10',
          id: 'la_palma',
          name: 'La Palma',
          name_es: 'La Palma',
          name_it: 'La Palma',
          source: ' Consejería de Sanidad Gobierno de Canarias',
          today_confirmed: 428,
          today_deaths: 0,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: null,
          yesterday_confirmed: 428,
          yesterday_deaths: 0,
        },
        {
          date: '2021-03-10',
          id: 'la_gomera',
          name: 'La Gomera',
          name_es: 'La Gomera',
          name_it: 'La Gomera',
          source: ' Consejería de Sanidad Gobierno de Canarias',
          today_confirmed: 218,
          today_deaths: 0,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: null,
          yesterday_confirmed: 218,
          yesterday_deaths: 0,
        },
        {
          date: '2021-03-10',
          id: 'lanzarote',
          name: 'Lanzarote',
          name_es: 'Lanzarote',
          name_it: 'Lanzarote',
          source: ' Consejería de Sanidad Gobierno de Canarias',
          today_confirmed: 4496,
          today_deaths: 0,
          today_new_confirmed: 11,
          today_new_deaths: 0,
          today_vs_yesterday_confirmed: 0.0024526198439240865,
          today_vs_yesterday_deaths: null,
          yesterday_confirmed: 4485,
          yesterday_deaths: 0,
        },
        {
          date: '2021-03-10',
          id: 'fuerteventura',
          name: 'Fuerteventura',
          name_es: 'Fuerteventura',
          name_it: 'Fuerteventura',
          source: ' Consejería de Sanidad Gobierno de Canarias',
          today_confirmed: 1782,
          today_deaths: 0,
          today_new_confirmed: 23,
          today_new_deaths: 0,
          today_vs_yesterday_confirmed: 0.013075611142694621,
          today_vs_yesterday_deaths: null,
          yesterday_confirmed: 1759,
          yesterday_deaths: 0,
        },
        {
          date: '2021-03-10',
          id: 'el_hierro',
          name: 'El Hierro',
          name_es: 'El Hierro',
          name_it: 'El Hierro',
          source: ' Consejería de Sanidad Gobierno de Canarias',
          today_confirmed: 296,
          today_deaths: 0,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: null,
          yesterday_confirmed: 296,
          yesterday_deaths: 0,
        },
        {
          date: '2021-03-10',
          id: 'gran_canaria',
          name: 'Gran Canaria',
          name_es: 'Gran Canaria',
          name_it: 'Gran Canaria',
          source: ' Consejería de Sanidad Gobierno de Canarias',
          today_confirmed: 17489,
          today_deaths: 0,
          today_new_confirmed: 76,
          today_new_deaths: 0,
          today_vs_yesterday_confirmed: 0.004364555217366339,
          today_vs_yesterday_deaths: null,
          yesterday_confirmed: 17413,
          yesterday_deaths: 0,
        },
      ],
      today_confirmed: 177575,
      today_deaths: 1190,
      today_intensive_care: 0,
      today_new_confirmed: 7451,
      today_new_deaths: 13,
      today_new_intensive_care: 0,
      today_new_open_cases: 7438,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 176385,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.04379746537819473,
      today_vs_yesterday_deaths: 0.011045029736618472,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.0440256411774107,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 170124,
      yesterday_deaths: 1177,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 168947,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'madrid',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/madrid',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Madrid',
      name_es: 'Madrid',
      name_it: 'Madrid',
      source: 'John Hopkins University',
      sub_regions: [],
      today_confirmed: 1206297,
      today_deaths: 16381,
      today_intensive_care: 0,
      today_new_confirmed: 21445,
      today_new_deaths: 3,
      today_new_intensive_care: 0,
      today_new_open_cases: 21442,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 1189916,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.018099306917657154,
      today_vs_yesterday_deaths: 0.0001831725485408331,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.01835042970575307,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 1184852,
      yesterday_deaths: 16378,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 1168474,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'murcia',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/murcia',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Murcia',
      name_es: 'Murcia',
      name_it: 'Murcia',
      source: 'John Hopkins University',
      sub_regions: [],
      today_confirmed: 198164,
      today_deaths: 1857,
      today_intensive_care: 0,
      today_new_confirmed: 6763,
      today_new_deaths: 4,
      today_new_intensive_care: 0,
      today_new_open_cases: 6759,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 196307,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.03533419365625057,
      today_vs_yesterday_deaths: 0.0021586616297895045,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.03565851393842201,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 191401,
      yesterday_deaths: 1853,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 189548,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'extremadura',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/extremadura',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Extremadura',
      name_es: 'Extremadura',
      name_it: 'Extremadura',
      source: 'John Hopkins University',
      sub_regions: [
        {
          date: '2021-08-27',
          id: 'area_de_salud_de_caceres',
          name: 'Área de Salud de Cáceres',
          name_es: 'Área de Salud de Cáceres',
          name_it: 'Área de Salud de Cáceres',
          source: 'Consejería de Sanidad y Servicios Sociales Junta de Extremadura',
          today_confirmed: 15734,
          today_deaths: 460,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_new_recovered: 2,
          today_recovered: 12279,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.00016290624745463056,
          yesterday_confirmed: 15734,
          yesterday_deaths: 460,
          yesterday_recovered: 12277,
        },
        {
          date: '2021-08-27',
          id: 'area_de_salud_de_badajoz',
          name: 'Área de Salud de Badajoz',
          name_es: 'Área de Salud de Badajoz',
          name_it: 'Área de Salud de Badajoz',
          source: 'Consejería de Sanidad y Servicios Sociales Junta de Extremadura',
          today_confirmed: 27321,
          today_deaths: 309,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 19702,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 27321,
          yesterday_deaths: 309,
          yesterday_recovered: 19702,
        },
        {
          date: '2021-08-27',
          id: 'area_de_salud_de_merida',
          name: 'Área de Salud de Mérida',
          name_es: 'Área de Salud de Mérida',
          name_it: 'Área de Salud de Mérida',
          source: 'Consejería de Sanidad y Servicios Sociales Junta de Extremadura',
          today_confirmed: 16855,
          today_deaths: 230,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 12414,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 16855,
          yesterday_deaths: 230,
          yesterday_recovered: 12414,
        },
        {
          date: '2021-08-27',
          id: 'area_de_salud_de_plasencia',
          name: 'Área de Salud de Plasencia',
          name_es: 'Área de Salud de Plasencia',
          name_it: 'Área de Salud de Plasencia',
          source: 'Consejería de Sanidad y Servicios Sociales Junta de Extremadura',
          today_confirmed: 10553,
          today_deaths: 187,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_new_recovered: 4117,
          today_recovered: 8713,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.8957789382071366,
          yesterday_confirmed: 10553,
          yesterday_deaths: 187,
          yesterday_recovered: 4596,
        },
        {
          date: '2021-08-27',
          id: 'area_de_salud_de_don_benito-villanueva_de_la_serena',
          name: 'Área de Salud de Don Benito-Villanueva de la Serena',
          name_es: 'Área de Salud de Don Benito-Villanueva de la Serena',
          name_it: 'Área de Salud de Don Benito-Villanueva de la Serena',
          source: 'Consejería de Sanidad y Servicios Sociales Junta de Extremadura',
          today_confirmed: 13316,
          today_deaths: 219,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_new_recovered: 5,
          today_recovered: 8713,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.0005741846577860255,
          yesterday_confirmed: 13316,
          yesterday_deaths: 219,
          yesterday_recovered: 8708,
        },
        {
          date: '2021-08-27',
          id: 'area_de_salud_navalmoral',
          name: 'Área de Salud Navalmoral',
          name_es: 'Área de Salud Navalmoral',
          name_it: 'Área de Salud Navalmoral',
          source: 'Consejería de Sanidad y Servicios Sociales Junta de Extremadura',
          today_confirmed: 4514,
          today_deaths: 108,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_new_recovered: 2,
          today_recovered: 3292,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.0006079027355623268,
          yesterday_confirmed: 4514,
          yesterday_deaths: 108,
          yesterday_recovered: 3290,
        },
        {
          date: '2021-08-27',
          id: 'area_de_salud_de_coria',
          name: 'Área de Salud de Coria',
          name_es: 'Área de Salud de Coria',
          name_it: 'Área de Salud de Coria',
          source: 'Consejería de Sanidad y Servicios Sociales Junta de Extremadura',
          today_confirmed: 3125,
          today_deaths: 81,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 2126,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 3125,
          yesterday_deaths: 81,
          yesterday_recovered: 2126,
        },
        {
          date: '2021-08-27',
          id: 'area_de_salud_de_llerena-zafra',
          name: 'Área de Salud de Llerena-Zafra',
          name_es: 'Área de Salud de Llerena-Zafra',
          name_it: 'Área de Salud de Llerena-Zafra',
          source: 'Consejería de Sanidad y Servicios Sociales Junta de Extremadura',
          today_confirmed: 7610,
          today_deaths: 119,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_new_recovered: 6,
          today_recovered: 5170,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.0011618900077459138,
          yesterday_confirmed: 7610,
          yesterday_deaths: 119,
          yesterday_recovered: 5164,
        },
      ],
      today_confirmed: 151836,
      today_deaths: 2029,
      today_intensive_care: 0,
      today_new_confirmed: 5223,
      today_new_deaths: 4,
      today_new_intensive_care: 0,
      today_new_open_cases: 5219,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 149807,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.03562439892778957,
      today_vs_yesterday_deaths: 0.0019753086419753707,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.036095664923783355,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 146613,
      yesterday_deaths: 2025,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 144588,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'andalucia',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/andalucia',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Andalucía',
      name_es: 'Andalucía',
      name_it: 'Andalucía',
      source: 'John Hopkins University',
      sub_regions: [
        {
          date: '2022-01-07',
          id: 'almeria',
          name: 'Almería',
          name_es: 'Almería',
          name_it: 'Almería',
          source: 'Consejería Salud y Familias Junta Andalucía',
          today_confirmed: 90106,
          today_deaths: 959,
          today_intensive_care: 814,
          today_new_confirmed: 1431,
          today_new_deaths: 0,
          today_new_intensive_care: 4,
          today_new_recovered: 15,
          today_new_total_hospitalised_patients: 1,
          today_recovered: 19112,
          today_total_hospitalised_patients: 4712,
          today_vs_yesterday_confirmed: 0.01613758105441221,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_intensive_care: 0.004938271604938205,
          today_vs_yesterday_recovered: 0.0007854636853956709,
          today_vs_yesterday_total_hospitalised_patients: 0.0002122691572914448,
          yesterday_confirmed: 88675,
          yesterday_deaths: 959,
          yesterday_intensive_care: 810,
          yesterday_recovered: 19097,
          yesterday_total_hospitalised_patients: 4711,
        },
        {
          date: '2022-01-07',
          id: 'cadiz',
          name: 'Cádiz',
          name_es: 'Cádiz',
          name_it: 'Cádiz',
          source: 'Consejería Salud y Familias Junta Andalucía',
          today_confirmed: 145042,
          today_deaths: 1635,
          today_intensive_care: 693,
          today_new_confirmed: 1883,
          today_new_deaths: 0,
          today_new_intensive_care: 0,
          today_new_recovered: 50,
          today_new_total_hospitalised_patients: 0,
          today_recovered: 27715,
          today_total_hospitalised_patients: 6814,
          today_vs_yesterday_confirmed: 0.013153207273032042,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_intensive_care: 0.0,
          today_vs_yesterday_recovered: 0.0018073377914331612,
          today_vs_yesterday_total_hospitalised_patients: 0.0,
          yesterday_confirmed: 143159,
          yesterday_deaths: 1635,
          yesterday_intensive_care: 693,
          yesterday_recovered: 27665,
          yesterday_total_hospitalised_patients: 6814,
        },
        {
          date: '2022-01-07',
          id: 'cordoba',
          name: 'Córdoba',
          name_es: 'Córdoba',
          name_it: 'Córdoba',
          source: 'Consejería Salud y Familias Junta Andalucía',
          today_confirmed: 104221,
          today_deaths: 1127,
          today_intensive_care: 711,
          today_new_confirmed: 1372,
          today_new_deaths: 0,
          today_new_intensive_care: 4,
          today_new_recovered: 45,
          today_new_total_hospitalised_patients: 15,
          today_recovered: 23584,
          today_total_hospitalised_patients: 5772,
          today_vs_yesterday_confirmed: 0.013339944967865502,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_intensive_care: 0.005657708628005631,
          today_vs_yesterday_recovered: 0.0019117209737031793,
          today_vs_yesterday_total_hospitalised_patients: 0.002605523710265789,
          yesterday_confirmed: 102849,
          yesterday_deaths: 1127,
          yesterday_intensive_care: 707,
          yesterday_recovered: 23539,
          yesterday_total_hospitalised_patients: 5757,
        },
        {
          date: '2022-01-07',
          id: 'granada',
          name: 'Granada',
          name_es: 'Granada',
          name_it: 'Granada',
          source: 'Consejería Salud y Familias Junta Andalucía',
          today_confirmed: 135849,
          today_deaths: 1900,
          today_intensive_care: 1196,
          today_new_confirmed: 1783,
          today_new_deaths: 0,
          today_new_intensive_care: 0,
          today_new_recovered: 52,
          today_new_total_hospitalised_patients: 0,
          today_recovered: 43058,
          today_total_hospitalised_patients: 9602,
          today_vs_yesterday_confirmed: 0.013299419688810099,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_intensive_care: 0.0,
          today_vs_yesterday_recovered: 0.0012091336092638905,
          today_vs_yesterday_total_hospitalised_patients: 0.0,
          yesterday_confirmed: 134066,
          yesterday_deaths: 1900,
          yesterday_intensive_care: 1196,
          yesterday_recovered: 43006,
          yesterday_total_hospitalised_patients: 9602,
        },
        {
          date: '2022-01-07',
          id: 'huelva',
          name: 'Huelva',
          name_es: 'Huelva',
          name_it: 'Huelva',
          source: 'Consejería Salud y Familias Junta Andalucía',
          today_confirmed: 59006,
          today_deaths: 427,
          today_intensive_care: 232,
          today_new_confirmed: 681,
          today_new_deaths: 0,
          today_new_intensive_care: 0,
          today_new_recovered: 27,
          today_new_total_hospitalised_patients: 0,
          today_recovered: 9934,
          today_total_hospitalised_patients: 3079,
          today_vs_yesterday_confirmed: 0.011675953707672493,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_intensive_care: 0.0,
          today_vs_yesterday_recovered: 0.0027253457151508176,
          today_vs_yesterday_total_hospitalised_patients: 0.0,
          yesterday_confirmed: 58325,
          yesterday_deaths: 427,
          yesterday_intensive_care: 232,
          yesterday_recovered: 9907,
          yesterday_total_hospitalised_patients: 3079,
        },
        {
          date: '2022-01-07',
          id: 'jaen',
          name: 'Jaén',
          name_es: 'Jaén',
          name_it: 'Jaén',
          source: 'Consejería Salud y Familias Junta Andalucía',
          today_confirmed: 84563,
          today_deaths: 1104,
          today_intensive_care: 508,
          today_new_confirmed: 1487,
          today_new_deaths: 0,
          today_new_intensive_care: 1,
          today_new_recovered: 65,
          today_new_total_hospitalised_patients: 0,
          today_recovered: 23276,
          today_total_hospitalised_patients: 5472,
          today_vs_yesterday_confirmed: 0.017899272954884582,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_intensive_care: 0.0019723865877712132,
          today_vs_yesterday_recovered: 0.002800396363793034,
          today_vs_yesterday_total_hospitalised_patients: 0.0,
          yesterday_confirmed: 83076,
          yesterday_deaths: 1104,
          yesterday_intensive_care: 507,
          yesterday_recovered: 23211,
          yesterday_total_hospitalised_patients: 5472,
        },
        {
          date: '2022-01-07',
          id: 'malaga',
          name: 'Málaga',
          name_es: 'Málaga',
          name_it: 'Málaga',
          source: 'Consejería Salud y Familias Junta Andalucía',
          today_confirmed: 203684,
          today_deaths: 2074,
          today_intensive_care: 1057,
          today_new_confirmed: 2403,
          today_new_deaths: 4,
          today_new_intensive_care: 0,
          today_new_recovered: 61,
          today_new_total_hospitalised_patients: 32,
          today_recovered: 36166,
          today_total_hospitalised_patients: 11370,
          today_vs_yesterday_confirmed: 0.011938533691704611,
          today_vs_yesterday_deaths: 0.0019323671497584183,
          today_vs_yesterday_intensive_care: 0.0,
          today_vs_yesterday_recovered: 0.0016895166874393297,
          today_vs_yesterday_total_hospitalised_patients: 0.0028223672605398598,
          yesterday_confirmed: 201281,
          yesterday_deaths: 2070,
          yesterday_intensive_care: 1057,
          yesterday_recovered: 36105,
          yesterday_total_hospitalised_patients: 11338,
        },
        {
          date: '2022-01-07',
          id: 'sevilla',
          name: 'Sevilla',
          name_es: 'Sevilla',
          name_it: 'Sevilla',
          source: 'Consejería Salud y Familias Junta Andalucía',
          today_confirmed: 226585,
          today_deaths: 2385,
          today_intensive_care: 1308,
          today_new_confirmed: 2673,
          today_new_deaths: 0,
          today_new_intensive_care: 0,
          today_new_recovered: 123,
          today_new_total_hospitalised_patients: 5,
          today_recovered: 55352,
          today_total_hospitalised_patients: 13576,
          today_vs_yesterday_confirmed: 0.011937725535031696,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_intensive_care: 0.0,
          today_vs_yesterday_recovered: 0.002227090839957313,
          today_vs_yesterday_total_hospitalised_patients: 0.000368432687348097,
          yesterday_confirmed: 223912,
          yesterday_deaths: 2385,
          yesterday_intensive_care: 1308,
          yesterday_recovered: 55229,
          yesterday_total_hospitalised_patients: 13571,
        },
      ],
      today_confirmed: 1041565,
      today_deaths: 11537,
      today_intensive_care: 0,
      today_new_confirmed: 25812,
      today_new_deaths: 11,
      today_new_intensive_care: 0,
      today_new_open_cases: 25801,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 1030028,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.025411689652897973,
      today_vs_yesterday_deaths: 0.0009543640465035086,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.025692398232670444,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 1015753,
      yesterday_deaths: 11526,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 1004227,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'castilla_y_leon',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/castilla_y_leon',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Castilla y León',
      name_es: 'Castilla y León',
      name_it: 'Castilla y León',
      source: 'John Hopkins University',
      sub_regions: [
        {
          date: '2022-01-07',
          id: 'avila',
          name: 'Ávila',
          name_es: 'Ávila',
          name_it: 'Ávila',
          source: 'Junta de Castilla y León ',
          today_confirmed: 26454,
          today_deaths: 408,
          today_new_confirmed: 416,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 2100,
          today_vs_yesterday_confirmed: 0.015976649512251306,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 26038,
          yesterday_deaths: 408,
          yesterday_recovered: 2100,
        },
        {
          date: '2022-01-07',
          id: 'burgos',
          name: 'Burgos',
          name_es: 'Burgos',
          name_it: 'Burgos',
          source: 'Junta de Castilla y León ',
          today_confirmed: 73766,
          today_deaths: 832,
          today_new_confirmed: 530,
          today_new_deaths: 0,
          today_new_recovered: 4,
          today_recovered: 5272,
          today_vs_yesterday_confirmed: 0.00723687803812334,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.0007593014426727773,
          yesterday_confirmed: 73236,
          yesterday_deaths: 832,
          yesterday_recovered: 5268,
        },
        {
          date: '2022-01-07',
          id: 'leon',
          name: 'León',
          name_es: 'León',
          name_it: 'León',
          source: 'Junta de Castilla y León ',
          today_confirmed: 74605,
          today_deaths: 1287,
          today_new_confirmed: 671,
          today_new_deaths: 4,
          today_new_recovered: 6,
          today_recovered: 6060,
          today_vs_yesterday_confirmed: 0.009075662076987623,
          today_vs_yesterday_deaths: 0.003117692907248726,
          today_vs_yesterday_recovered: 0.0009910802775023875,
          yesterday_confirmed: 73934,
          yesterday_deaths: 1283,
          yesterday_recovered: 6054,
        },
        {
          date: '2022-01-07',
          id: 'palencia',
          name: 'Palencia',
          name_es: 'Palencia',
          name_it: 'Palencia',
          source: 'Junta de Castilla y León ',
          today_confirmed: 36933,
          today_deaths: 520,
          today_new_confirmed: 365,
          today_new_deaths: 1,
          today_new_recovered: 3,
          today_recovered: 2704,
          today_vs_yesterday_confirmed: 0.009981404506672398,
          today_vs_yesterday_deaths: 0.0019267822736031004,
          today_vs_yesterday_recovered: 0.0011106997408367736,
          yesterday_confirmed: 36568,
          yesterday_deaths: 519,
          yesterday_recovered: 2701,
        },
        {
          date: '2022-01-07',
          id: 'salamanca',
          name: 'Salamanca',
          name_es: 'Salamanca',
          name_it: 'Salamanca',
          source: 'Junta de Castilla y León ',
          today_confirmed: 58921,
          today_deaths: 919,
          today_new_confirmed: 522,
          today_new_deaths: 2,
          today_new_recovered: 5,
          today_recovered: 4573,
          today_vs_yesterday_confirmed: 0.00893850922104833,
          today_vs_yesterday_deaths: 0.0021810250817884125,
          today_vs_yesterday_recovered: 0.0010945709281962035,
          yesterday_confirmed: 58399,
          yesterday_deaths: 917,
          yesterday_recovered: 4568,
        },
        {
          date: '2022-01-07',
          id: 'segovia',
          name: 'Segovia',
          name_es: 'Segovia',
          name_it: 'Segovia',
          source: 'Junta de Castilla y León ',
          today_confirmed: 31250,
          today_deaths: 387,
          today_new_confirmed: 342,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 2098,
          today_vs_yesterday_confirmed: 0.011065096415167508,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 30908,
          yesterday_deaths: 387,
          yesterday_recovered: 2098,
        },
        {
          date: '2022-01-07',
          id: 'soria',
          name: 'Soria',
          name_es: 'Soria',
          name_it: 'Soria',
          source: 'Junta de Castilla y León ',
          today_confirmed: 17867,
          today_deaths: 304,
          today_new_confirmed: 147,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 1469,
          today_vs_yesterday_confirmed: 0.008295711060948063,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 17720,
          yesterday_deaths: 304,
          yesterday_recovered: 1469,
        },
        {
          date: '2022-01-07',
          id: 'valladolid',
          name: 'Valladolid',
          name_es: 'Valladolid',
          name_it: 'Valladolid',
          source: 'Junta de Castilla y León ',
          today_confirmed: 108302,
          today_deaths: 1347,
          today_new_confirmed: 1139,
          today_new_deaths: 2,
          today_new_recovered: 7,
          today_recovered: 8804,
          today_vs_yesterday_confirmed: 0.010628668476992953,
          today_vs_yesterday_deaths: 0.0014869888475836923,
          today_vs_yesterday_recovered: 0.0007957258156190417,
          yesterday_confirmed: 107163,
          yesterday_deaths: 1345,
          yesterday_recovered: 8797,
        },
        {
          date: '2022-01-07',
          id: 'zamora',
          name: 'Zamora',
          name_es: 'Zamora',
          name_it: 'Zamora',
          source: 'Junta de Castilla y León ',
          today_confirmed: 25659,
          today_deaths: 479,
          today_new_confirmed: 223,
          today_new_deaths: 2,
          today_new_recovered: 2,
          today_recovered: 2306,
          today_vs_yesterday_confirmed: 0.008767101745557504,
          today_vs_yesterday_deaths: 0.004192872117400492,
          today_vs_yesterday_recovered: 0.0008680555555555802,
          yesterday_confirmed: 25436,
          yesterday_deaths: 477,
          yesterday_recovered: 2304,
        },
      ],
      today_confirmed: 448333,
      today_deaths: 7583,
      today_intensive_care: 0,
      today_new_confirmed: 15413,
      today_new_deaths: 5,
      today_new_intensive_care: 0,
      today_new_open_cases: 15408,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 440750,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.03560242077058118,
      today_vs_yesterday_deaths: 0.0006598046978094629,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.03622496720286272,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 432920,
      yesterday_deaths: 7578,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 425342,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'c_valenciana',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/c_valenciana',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'C. Valenciana',
      name_es: 'C. Valenciana',
      name_it: 'C. Valenciana',
      source: 'John Hopkins University',
      sub_regions: [
        {
          date: '2022-01-07',
          id: 'alicante',
          name: 'Alicante',
          name_es: 'Alicante',
          name_it: 'Alicante',
          source: 'Consellera de Sanidad Universal y Salud Pública Generalitat Valenciana',
          today_confirmed: 257132,
          today_deaths: 2614,
          today_new_confirmed: 257132,
          today_new_deaths: 8,
          today_new_recovered: 182,
          today_recovered: 142951,
          today_vs_yesterday_confirmed: null,
          today_vs_yesterday_deaths: 0.003069838833461347,
          today_vs_yesterday_recovered: 0.0012747865432971572,
          yesterday_confirmed: 0,
          yesterday_deaths: 2606,
          yesterday_recovered: 142769,
        },
        {
          date: '2022-01-07',
          id: 'castellon',
          name: 'Castellón',
          name_es: 'Castellón',
          name_it: 'Castellón',
          source: 'Consellera de Sanidad Universal y Salud Pública Generalitat Valenciana',
          today_confirmed: 80496,
          today_deaths: 769,
          today_new_confirmed: 80496,
          today_new_deaths: 3,
          today_new_recovered: 70,
          today_recovered: 39235,
          today_vs_yesterday_confirmed: null,
          today_vs_yesterday_deaths: 0.003916449086161844,
          today_vs_yesterday_recovered: 0.0017873100983021306,
          yesterday_confirmed: 0,
          yesterday_deaths: 766,
          yesterday_recovered: 39165,
        },
        {
          date: '2022-01-07',
          id: 'valencia',
          name: 'Valencia',
          name_es: 'Valencia',
          name_it: 'Valencia',
          source: 'Consellera de Sanidad Universal y Salud Pública Generalitat Valenciana',
          today_confirmed: 375355,
          today_deaths: 3566,
          today_new_confirmed: 375355,
          today_new_deaths: 27,
          today_new_recovered: 256,
          today_recovered: 199146,
          today_vs_yesterday_confirmed: null,
          today_vs_yesterday_deaths: 0.007629273806159853,
          today_vs_yesterday_recovered: 0.0012871436472421394,
          yesterday_confirmed: 0,
          yesterday_deaths: 3539,
          yesterday_recovered: 198890,
        },
      ],
      today_confirmed: 713156,
      today_deaths: 8170,
      today_intensive_care: 0,
      today_new_confirmed: 28846,
      today_new_deaths: 9,
      today_new_intensive_care: 0,
      today_new_open_cases: 28837,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 704986,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.04215341000423778,
      today_vs_yesterday_deaths: 0.0011028060286728536,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.04264888360405772,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 684310,
      yesterday_deaths: 8161,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 676149,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'la_rioja',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/la_rioja',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'La Rioja',
      name_es: 'La Rioja',
      name_it: 'La Rioja',
      source: 'John Hopkins University',
      sub_regions: [],
      today_confirmed: 59541,
      today_deaths: 853,
      today_intensive_care: 0,
      today_new_confirmed: 2518,
      today_new_deaths: 2,
      today_new_intensive_care: 0,
      today_new_open_cases: 2516,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 58688,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.04415762060922779,
      today_vs_yesterday_deaths: 0.00235017626321965,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.044790999074271864,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 57023,
      yesterday_deaths: 851,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 56172,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'melilla',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/melilla',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Melilla',
      name_es: 'Melilla',
      name_it: 'Melilla',
      source: 'John Hopkins University',
      sub_regions: [],
      today_confirmed: 14098,
      today_deaths: 122,
      today_intensive_care: 0,
      today_new_confirmed: 436,
      today_new_deaths: 0,
      today_new_intensive_care: 0,
      today_new_open_cases: 436,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 13976,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.03191333626116233,
      today_vs_yesterday_deaths: 0.0,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.03220088626292461,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 13662,
      yesterday_deaths: 122,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 13540,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'cantabria',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/cantabria',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Cantabria',
      name_es: 'Cantabria',
      name_it: 'Cantabria',
      source: 'John Hopkins University',
      sub_regions: [],
      today_confirmed: 71293,
      today_deaths: 632,
      today_intensive_care: 0,
      today_new_confirmed: 3625,
      today_new_deaths: 2,
      today_new_intensive_care: 0,
      today_new_open_cases: 3623,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 70661,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.0535703729975765,
      today_vs_yesterday_deaths: 0.0031746031746031633,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.05404397505892189,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 67668,
      yesterday_deaths: 630,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 67038,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'pais_vasco',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/pais_vasco',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'País Vasco',
      name_es: 'País Vasco',
      name_it: 'País Vasco',
      source: 'John Hopkins University',
      sub_regions: [
        {
          date: '2022-01-05',
          id: 'alava',
          name: 'Álava',
          name_es: 'Álava',
          name_it: 'Álava',
          source: 'Departamento Salud Gobierno País Vasco',
          today_confirmed: 61506,
          today_deaths: 0,
          today_new_confirmed: 2005,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 0,
          today_vs_yesterday_confirmed: 0.0336969126569302,
          today_vs_yesterday_deaths: null,
          today_vs_yesterday_recovered: null,
          yesterday_confirmed: 59501,
          yesterday_deaths: 0,
          yesterday_recovered: 0,
        },
        {
          date: '2022-01-05',
          id: 'bizkaia',
          name: 'Bizkaia',
          name_es: 'Bizkaia',
          name_it: 'Bizkaia',
          source: 'Departamento Salud Gobierno País Vasco',
          today_confirmed: 224590,
          today_deaths: 0,
          today_new_confirmed: 7197,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 0,
          today_vs_yesterday_confirmed: 0.03310594177365411,
          today_vs_yesterday_deaths: null,
          today_vs_yesterday_recovered: null,
          yesterday_confirmed: 217393,
          yesterday_deaths: 0,
          yesterday_recovered: 0,
        },
        {
          date: '2022-01-05',
          id: 'gipuzkoa',
          name: 'Gipuzkoa',
          name_es: 'Gipuzkoa',
          name_it: 'Gipuzkoa',
          source: 'Departamento Salud Gobierno País Vasco',
          today_confirmed: 163611,
          today_deaths: 0,
          today_new_confirmed: 3934,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 0,
          today_vs_yesterday_confirmed: 0.024637236421025,
          today_vs_yesterday_deaths: null,
          today_vs_yesterday_recovered: null,
          yesterday_confirmed: 159677,
          yesterday_deaths: 0,
          yesterday_recovered: 0,
        },
      ],
      today_confirmed: 450442,
      today_deaths: 5192,
      today_intensive_care: 0,
      today_new_confirmed: 22119,
      today_new_deaths: 0,
      today_new_intensive_care: 0,
      today_new_open_cases: 22119,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 445250,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.0516409345283817,
      today_vs_yesterday_deaths: 0.0,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.052274591084085165,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 428323,
      yesterday_deaths: 5192,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 423131,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'aragon',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/aragon',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Aragón',
      name_es: 'Aragón',
      name_it: 'Aragón',
      source: 'John Hopkins University',
      sub_regions: [
        {
          date: '2022-01-05',
          id: 'zaragoza',
          name: 'Zaragoza',
          name_es: 'Zaragoza',
          name_it: 'Zaragoza',
          source: 'Dirección General de Salud Pública Gobierno Aragón',
          today_confirmed: 183609,
          today_deaths: 0,
          today_new_confirmed: 5916,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 0,
          today_vs_yesterday_confirmed: 0.03329337677905153,
          today_vs_yesterday_deaths: null,
          today_vs_yesterday_recovered: null,
          yesterday_confirmed: 177693,
          yesterday_deaths: 0,
          yesterday_recovered: 0,
        },
        {
          date: '2022-01-05',
          id: 'huesca',
          name: 'Huesca',
          name_es: 'Huesca',
          name_it: 'Huesca',
          source: 'Dirección General de Salud Pública Gobierno Aragón',
          today_confirmed: 42095,
          today_deaths: 0,
          today_new_confirmed: 959,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 0,
          today_vs_yesterday_confirmed: 0.023312913263321633,
          today_vs_yesterday_deaths: null,
          today_vs_yesterday_recovered: null,
          yesterday_confirmed: 41136,
          yesterday_deaths: 0,
          yesterday_recovered: 0,
        },
        {
          date: '2022-01-05',
          id: 'teruel',
          name: 'Teruel',
          name_es: 'Teruel',
          name_it: 'Teruel',
          source: 'Dirección General de Salud Pública Gobierno Aragón',
          today_confirmed: 23887,
          today_deaths: 0,
          today_new_confirmed: 577,
          today_new_deaths: 0,
          today_new_recovered: 0,
          today_recovered: 0,
          today_vs_yesterday_confirmed: 0.0247533247533247,
          today_vs_yesterday_deaths: null,
          today_vs_yesterday_recovered: null,
          yesterday_confirmed: 23310,
          yesterday_deaths: 0,
          yesterday_recovered: 0,
        },
      ],
      today_confirmed: 254032,
      today_deaths: 4137,
      today_intensive_care: 0,
      today_new_confirmed: 10085,
      today_new_deaths: 9,
      today_new_intensive_care: 0,
      today_new_open_cases: 10076,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 249895,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.04134094700898139,
      today_vs_yesterday_deaths: 0.0021802325581394832,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.04201501966066079,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 243947,
      yesterday_deaths: 4128,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 239819,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'asturias',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/asturias',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Asturias',
      name_es: 'Asturias',
      name_it: 'Asturias',
      source: 'John Hopkins University',
      sub_regions: [],
      today_confirmed: 113025,
      today_deaths: 2185,
      today_intensive_care: 0,
      today_new_confirmed: 4805,
      today_new_deaths: 7,
      today_new_intensive_care: 0,
      today_new_open_cases: 4798,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 110840,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.04440029569395665,
      today_vs_yesterday_deaths: 0.003213957759412356,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.04524622319458338,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 108220,
      yesterday_deaths: 2178,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 106042,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'navarra',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/navarra',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Navarra',
      name_es: 'Navarra',
      name_it: 'Navarra',
      source: 'John Hopkins University',
      sub_regions: [],
      today_confirmed: 152302,
      today_deaths: 1310,
      today_intensive_care: 0,
      today_new_confirmed: 5952,
      today_new_deaths: 1,
      today_new_intensive_care: 0,
      today_new_open_cases: 5951,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 150992,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.040669627605056435,
      today_vs_yesterday_deaths: 0.0007639419404126269,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.04102977778697059,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 146350,
      yesterday_deaths: 1309,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 145041,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'baleares',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/baleares',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Baleares',
      name_es: 'Baleares',
      name_it: 'Baleares',
      source: 'John Hopkins University',
      sub_regions: [],
      today_confirmed: 149317,
      today_deaths: 1069,
      today_intensive_care: 0,
      today_new_confirmed: 5579,
      today_new_deaths: 0,
      today_new_intensive_care: 0,
      today_new_open_cases: 5579,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 148248,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.03881367488068577,
      today_vs_yesterday_deaths: 0.0,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.03910450062732629,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 143738,
      yesterday_deaths: 1069,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 142669,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'cataluna',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/cataluna',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Cataluña',
      name_es: 'Cataluña',
      name_it: 'Cataluña',
      source: 'John Hopkins University',
      sub_regions: [
        {
          date: '2022-01-06',
          id: 'barcelona',
          name: 'Barcelona',
          name_es: 'Barcelona',
          name_it: 'Barcelona',
          source: 'Generalitat de Catalunya',
          today_confirmed: 1059584,
          today_new_confirmed: 3136,
          today_vs_yesterday_confirmed: 0.002968437632519638,
          yesterday_confirmed: 1056448,
        },
        {
          date: '2022-01-06',
          id: 'gerona',
          name: 'Gerona',
          name_es: 'Gerona',
          name_it: 'Gerona',
          source: 'Generalitat de Catalunya',
          today_confirmed: 135489,
          today_new_confirmed: 569,
          today_vs_yesterday_confirmed: 0.004217313963830405,
          yesterday_confirmed: 134920,
        },
        {
          date: '2022-01-06',
          id: 'lerida',
          name: 'Lérida',
          name_es: 'Lérida',
          name_it: 'Lérida',
          source: 'Generalitat de Catalunya',
          today_confirmed: 81345,
          today_new_confirmed: 403,
          today_vs_yesterday_confirmed: 0.004978873761458891,
          yesterday_confirmed: 80942,
        },
        {
          date: '2022-01-06',
          id: 'tarragona',
          name: 'Tarragona',
          name_es: 'Tarragona',
          name_it: 'Tarragona',
          source: 'Generalitat de Catalunya',
          today_confirmed: 115621,
          today_new_confirmed: 619,
          today_vs_yesterday_confirmed: 0.005382515086694184,
          yesterday_confirmed: 115002,
        },
      ],
      today_confirmed: 1333517,
      today_deaths: 16144,
      today_intensive_care: 0,
      today_new_confirmed: 47345,
      today_new_deaths: 1,
      today_new_intensive_care: 0,
      today_new_open_cases: 47344,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 1317373,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.03681078424969608,
      today_vs_yesterday_deaths: 6.194635445710972e-05,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.037277888930095315,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 1286172,
      yesterday_deaths: 16143,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 1270029,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'galicia',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/galicia',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Galicia',
      name_es: 'Galicia',
      name_it: 'Galicia',
      source: 'John Hopkins University',
      sub_regions: [
        {
          date: '2022-01-07',
          id: 'area_sanitaria_a_coruna',
          name: 'Área sanitaria A Coruña',
          name_es: 'Área sanitaria A Coruña',
          name_it: 'Área sanitaria A Coruña',
          source: 'Consellería de Sanidad Xunta de Galicia',
          today_confirmed: 59763,
          today_new_confirmed: 452,
          today_vs_yesterday_confirmed: 0.00762084604879365,
          yesterday_confirmed: 59311,
        },
        {
          date: '2022-01-07',
          id: 'area_sanitaria_lugo',
          name: 'Área sanitaria Lugo',
          name_es: 'Área sanitaria Lugo',
          name_it: 'Área sanitaria Lugo',
          source: 'Consellería de Sanidad Xunta de Galicia',
          today_confirmed: 28770,
          today_new_confirmed: 264,
          today_vs_yesterday_confirmed: 0.00926120816670184,
          yesterday_confirmed: 28506,
        },
        {
          date: '2022-01-07',
          id: 'area_sanitaria_ourense',
          name: 'Área sanitaria Ourense',
          name_es: 'Área sanitaria Ourense',
          name_it: 'Área sanitaria Ourense',
          source: 'Consellería de Sanidad Xunta de Galicia',
          today_confirmed: 35660,
          today_new_confirmed: 426,
          today_vs_yesterday_confirmed: 0.012090594312311964,
          yesterday_confirmed: 35234,
        },
        {
          date: '2022-01-07',
          id: 'area_sanitaria_pontevedra',
          name: 'Área sanitaria Pontevedra',
          name_es: 'Área sanitaria Pontevedra',
          name_it: 'Área sanitaria Pontevedra',
          source: 'Consellería de Sanidad Xunta de Galicia',
          today_confirmed: 33322,
          today_new_confirmed: 235,
          today_vs_yesterday_confirmed: 0.007102487381751121,
          yesterday_confirmed: 33087,
        },
        {
          date: '2022-01-07',
          id: 'area_sanitaria_vigo',
          name: 'Área sanitaria Vigo',
          name_es: 'Área sanitaria Vigo',
          name_it: 'Área sanitaria Vigo',
          source: 'Consellería de Sanidad Xunta de Galicia',
          today_confirmed: 61468,
          today_new_confirmed: 447,
          today_vs_yesterday_confirmed: 0.007325347011684524,
          yesterday_confirmed: 61021,
        },
        {
          date: '2022-01-07',
          id: 'area_sanitaria_santiago',
          name: 'Área sanitaria Santiago',
          name_es: 'Área sanitaria Santiago',
          name_it: 'Área sanitaria Santiago',
          source: 'Consellería de Sanidad Xunta de Galicia',
          today_confirmed: 42004,
          today_new_confirmed: 486,
          today_vs_yesterday_confirmed: 0.011705766173707888,
          yesterday_confirmed: 41518,
        },
        {
          date: '2022-01-07',
          id: 'area_sanitaria_ferrol',
          name: 'Área sanitaria Ferrol',
          name_es: 'Área sanitaria Ferrol',
          name_it: 'Área sanitaria Ferrol',
          source: 'Consellería de Sanidad Xunta de Galicia',
          today_confirmed: 17089,
          today_new_confirmed: 143,
          today_vs_yesterday_confirmed: 0.008438569573940846,
          yesterday_confirmed: 16946,
        },
      ],
      today_confirmed: 293755,
      today_deaths: 2798,
      today_intensive_care: 0,
      today_new_confirmed: 13757,
      today_new_deaths: 18,
      today_new_intensive_care: 0,
      today_new_open_cases: 13739,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 290957,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.04913249380352713,
      today_vs_yesterday_deaths: 0.006474820143884896,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.0495602738638905,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 279998,
      yesterday_deaths: 2780,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 277218,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'castilla-la_mancha',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/castilla-la_mancha',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Castilla-La Mancha',
      name_es: 'Castilla-La Mancha',
      name_it: 'Castilla-La Mancha',
      source: 'John Hopkins University',
      sub_regions: [
        {
          date: '2021-03-10',
          id: 'ciudad_real',
          name: 'Ciudad Real',
          name_es: 'Ciudad Real',
          name_it: 'Ciudad Real',
          source: 'Consejería Salud Castilla-La Mancha',
          today_confirmed: 42752,
          today_deaths: 1676,
          today_new_confirmed: 30,
          today_new_deaths: 0,
          today_vs_yesterday_confirmed: 0.0007022143158090799,
          today_vs_yesterday_deaths: 0.0,
          yesterday_confirmed: 42722,
          yesterday_deaths: 1676,
        },
        {
          date: '2021-03-10',
          id: 'albacete',
          name: 'Albacete',
          name_es: 'Albacete',
          name_it: 'Albacete',
          source: 'Consejería Salud Castilla-La Mancha',
          today_confirmed: 27764,
          today_deaths: 872,
          today_new_confirmed: 19,
          today_new_deaths: 1,
          today_vs_yesterday_confirmed: 0.000684808073526666,
          today_vs_yesterday_deaths: 0.0011481056257176547,
          yesterday_confirmed: 27745,
          yesterday_deaths: 871,
        },
        {
          date: '2021-03-10',
          id: 'toledo',
          name: 'Toledo',
          name_es: 'Toledo',
          name_it: 'Toledo',
          source: 'Consejería Salud Castilla-La Mancha',
          today_confirmed: 62400,
          today_deaths: 2077,
          today_new_confirmed: 62,
          today_new_deaths: 2,
          today_vs_yesterday_confirmed: 0.0009945779460360793,
          today_vs_yesterday_deaths: 0.0009638554216866435,
          yesterday_confirmed: 62338,
          yesterday_deaths: 2075,
        },
        {
          date: '2021-03-10',
          id: 'guadalajara',
          name: 'Guadalajara',
          name_es: 'Guadalajara',
          name_it: 'Guadalajara',
          source: 'Consejería Salud Castilla-La Mancha',
          today_confirmed: 21090,
          today_deaths: 585,
          today_new_confirmed: 55,
          today_new_deaths: 0,
          today_vs_yesterday_confirmed: 0.0026146898027097354,
          today_vs_yesterday_deaths: 0.0,
          yesterday_confirmed: 21035,
          yesterday_deaths: 585,
        },
        {
          date: '2021-03-10',
          id: 'cuenca',
          name: 'Cuenca',
          name_es: 'Cuenca',
          name_it: 'Cuenca',
          source: 'Consejería Salud Castilla-La Mancha',
          today_confirmed: 17990,
          today_deaths: 533,
          today_new_confirmed: 2,
          today_new_deaths: 1,
          today_vs_yesterday_confirmed: 0.00011118523460074137,
          today_vs_yesterday_deaths: 0.001879699248120259,
          yesterday_confirmed: 17988,
          yesterday_deaths: 532,
        },
      ],
      today_confirmed: 326076,
      today_deaths: 6612,
      today_intensive_care: 0,
      today_new_confirmed: 14890,
      today_new_deaths: 7,
      today_new_intensive_care: 0,
      today_new_open_cases: 14883,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 319464,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.04784919630060469,
      today_vs_yesterday_deaths: 0.0010598031794095686,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.04886384902538232,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 311186,
      yesterday_deaths: 6605,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 304581,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
    {
      date: '2022-01-07',
      id: 'ceuta',
      links: [
        {
          href: '/api/2022-01-08/country/spain/region/ceuta',
          rel: 'self',
          type: 'GET',
        },
      ],
      name: 'Ceuta',
      name_es: 'Ceuta',
      name_it: 'Ceuta',
      source: 'John Hopkins University',
      sub_regions: [],
      today_confirmed: 10582,
      today_deaths: 133,
      today_intensive_care: 0,
      today_new_confirmed: 376,
      today_new_deaths: 1,
      today_new_intensive_care: 0,
      today_new_open_cases: 375,
      today_new_recovered: null,
      today_new_total_hospitalised_patients: 0,
      today_open_cases: 10449,
      today_recovered: null,
      today_total_hospitalised_patients: 0,
      today_vs_yesterday_confirmed: 0.036841073878110864,
      today_vs_yesterday_deaths: 0.007575757575757569,
      today_vs_yesterday_intensive_care: null,
      today_vs_yesterday_open_cases: 0.03722453841572371,
      today_vs_yesterday_recovered: null,
      today_vs_yesterday_total_hospitalised_patients: null,
      yesterday_confirmed: 10206,
      yesterday_deaths: 132,
      yesterday_intensive_care: 0,
      yesterday_open_cases: 10074,
      yesterday_recovered: null,
      yesterday_total_hospitalised_patients: 0,
    },
  ];

  it('Should be rendering 19 regions', () => {
    render(<BrowserRouter><Search data={data} /></BrowserRouter>);

    expect(data.length).toBe(19);
  });

  it('Should be rendering only 4 regions', () => {
    const data = [
      {
        id: 'MockState1',
        today_confirmed: 241846,
      },
      {
        id: 'MockState2',
        today_confirmed: 241846,
      },
      {
        id: 'MockState3',
        today_confirmed: 241846,
      },
      {
        id: 'MockState4',
        today_confirmed: 241846,
      },
    ];
    render(<BrowserRouter><Search data={data} /></BrowserRouter>);

    expect(data.length).toBe(4);
  });

  it('Component has Madrid', () => {
    render(<BrowserRouter><Search data={data} /></BrowserRouter>);

    expect(screen.getByText(/Madrid/i)).toBeInTheDocument();
  });

  it('Component has rid', () => {
    render(<BrowserRouter><Search data={data} /></BrowserRouter>);

    expect(screen.getByText(/Madrid/i)).toBeInTheDocument();
  });
});
